# Use an official Python runtime as a parent image
FROM python:3.7.4

ADD requirements_to_host.txt .
COPY prod_settings.py .

# Install any needed packages specified in requirements.txt
COPY katanaframework-1.2.0-py3-none-any.whl .
RUN apt-get update  && \
    apt-get install -y libsasl2-dev python-dev libldap2-dev libssl-dev psmisc libpq-dev  && \
    apt-get -y install python3-pip  && \
    rm -rf /var/lib/apt/lists/* && \
    pip install -r /requirements_to_host.txt  && \
    pip install katanaframework-1.2.0-py3-none-any.whl  && \
    cat prod_settings.py >> /usr/local/lib/python3.7/site-packages/katana/wui/settings.py 


COPY apps /apps
COPY /apps/InstallApp.json katana/katana_configs/app_config.json

