apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: ml/backend
    context: .
    docker: 
      dockerfile: dockerfile_uwsgi
  - image: ml/frontend
    context: .
    docker:
      dockerfile: dockerfile_nginx
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: ml-angular-userinterface
        chartPath: charts/ml-angular-userinterface
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'
