# Note : SOCKET_SCHEDULER_EXP_TIME is in minutes [ 60 to 4320 (3 days) | recommended : 360 ]
# Note : In EL_URL replace modelName value with '_vaxModelNamevax_' for dynamizing the url in UI
# Note : In FORECAST_GRAFANA_URL replace data Id value with '_vax_var-PM_name_vax_' for dynamizing the url in UI
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2020-04-06T18:52:05Z
  name: {{ .Values.configMap.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"

data:
  warrior_conf.conf: |
    [WARRIOR]
    FORECAST_POD=30920
    FORECAST_ORDERID=1
    FORECAST_GRAFANA=32300/d/CijHdYGMk/pm_forcast_1 
    FORECAST_GRAFANA_URL=32300/d/CijHdYGMk/pm_forcast_1?orgId=1&orderId=1&var-PM_name=_vax_var-PM_name_vax_&kiosk=tv&refresh=5s
    ANOMALY_POD=30807
    SCHEDULER_POD=30189
    CORRELATION_POD=30065
    CLASSIFICATION_POD=31126
    DATAINSIGHT_POD=31007
    FORECAST_SOCKET=31005/socket
    ANOMALY_SOCKET=31006/socket
    PROFILER_SOCKET=31004/socket
    DATAINSIGHT_SOCKET=31005/socket
    ANOMALY_PROFILER=anomaly_profiler*
    CLASSIFICATION_PROFILER=basic_profiler*
    SOCKET_SCHEDULER_EXP_TIME=360
    EL_POD=32101
    EL_URL=/app/dashboards#/view/093906e0-6d22-11eb-933b-df15118cab21?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1M,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'9ffb3930-6468-11eb-80b3-01f3d29be0ec',key:kafka_consumer.modelName,negate:!f,params:(query:'_vaxModelNamevax_'),type:phrase),query:(match_phrase:(kafka_consumer.modelName:'_vaxModelNamevax_')))),fullScreenMode:!t,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:''),timeRestore:!f,title:'Loss Histogram',viewMode:view)
