export const DATAMANAGEMENT_URLS = {
    GET_DATAINSIGHT_JOBTYPE_API: 'getJobTypeList/',
    GET_DATAINSIGHT_PROPERTYTYPE_API: 'getPropertyTypeList/',
    POST_DATAINSIGHT_DATAPREVIEW_API: 'getDataPreviewDetails/',
    GET_DATAINSIGHT_CONFIGURATION_API: 'getConfigurationList/',
    GET_DATAINSIGHT_CONFIGDET_API: 'getConfigurationDet/',
    POST_DATAINSIGHT_STEPS_API: 'getStepsDetails/',
    POST_DATAINSIGHT_FETCH_FEATURES_API: 'getFeatureDet/',
    POST_DATAINSIGHT_CREATE_DATA_SET_API: 'createDataSet/',
    PUT_DATAINSIGHT_UPDATE_DATA_SET_API: 'updateDataSet/',
    POST_DATAINSIGHT_FILE_UPLOAD_API: 'fileUploadDataSet/',
    POST_DATAINSIGHT_STREAM_SCHEDULE_API: 'streamDataSchedule/',
    GET_DATAINSIGHT_STREAM_SCHEDULE_API: 'getStreamScheduleStatus/',
    GET_CONFIGURATION_TABLEVIEW_API: 'getConfigurationTableview/',
    GET_CONFIGURATION_DETAILEDVIEW_API: 'getConfigurationDetailedView/',
    GET_CONFIGURATION_DBTYPE_API: 'getConfigurationDBType/',
    CREATE_CONFIGURATION_API: 'createConfiguration/',
    CREATE_NEWDBYTYPE_API: 'createNewDBType/',
    GET_DATA_SOURCE_LIST_API: 'getDataSourceList/',
    GET_DATA_SOURCE_DETAILS_API: 'getDataSource/',
    DELETE_DATA_SOURCE_API: 'deleteDataSource/',
    DELETE_CONFIGURATION: 'deleteConfiguration/',
    UPDATE_CONFIGURATION: 'updateConfiguration/'
};
